spring:
  application:
    name: RentalMovies
  datasource:
    url: jdbc:mysql://mysql:3306/rentalmovies?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
